packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  inlined:
    '@antfu/utils': ^9.2.1
    '@babel/generator': ^7.28.3
    '@babel/types': ^7.28.4
    '@vue/compiler-sfc': ^3.5.22
    ast-kit: ^2.1.3
    chokidar: ^4.0.3
    fs-extra: ^11.2.0
    jsonc-parser: ^3.3.1
    magic-string-ast: ^0.7.0
    picomatch: ^4.0.3
    rsync: ~0.6.1
    vue: ^3.5.22
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/babel__generator': ^7.6.7
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.5.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
